packages:
  - apps/*
  - packages/*
catalog:
  "@eslint/js": ^9.30.1
  "@ianvs/prettier-plugin-sort-imports": ^4.4.2
  "@react-router/architect": ^7.6.3
  "@react-router/dev": ^7.5.3
  "@react-router/node": ^7.5.3
  "@react-router/serve": ^7.5.3
  "@semantic-release/changelog": ^6.0.3
  "@semantic-release/commit-analyzer": ^13.0.1
  "@semantic-release/git": ^10.0.1
  "@semantic-release/github": ^11.0.3
  "@semantic-release/npm": ^12.0.2
  "@semantic-release/release-notes-generator": ^14.0.3
  "@tailwindcss/vite": ^4.1.4
  "@types/react": ^19.1.2
  "@types/react-dom": ^19.1.2
  "@typescript-eslint/eslint-plugin": ^8.35.1
  "@typescript-eslint/parser": ^8.35.1
  aws-cdk: ^2.1020.2
  aws-cdk-lib: ^2.204.0
  constructs: ^10.4.2
  dotenv: ^17.0.1
  dotenv-cli: ^8.0.0
  esbuild: ^0.25.5
  eslint: ^9.30.1
  eslint-plugin-unused-imports: ^4.1.4
  globals: ^16.3.0
  husky: ^9.1.7
  isbot: ^5.1.27
  prettier: ^3.6.2
  prettier-plugin-classnames: ^0.8.1
  prettier-plugin-css-order: ^2.1.2
  react: ^19.1.0
  react-dom: ^19.1.0
  react-router: ^7.5.3
  semantic-release: ^24.2.6
  tailwindcss: ^4.1.4
  tsx: ^4.20.3
  turbo: ^2.5.4
  typescript: ^5.8.3
  typescript-eslint: ^8.35.1
  vite: ^6.3.3
  vite-tsconfig-paths: ^5.1.4
